server:
  port: 8001

spring:
  application:
    name: clusterEureka
  profiles: cluster1

eureka:
  instance:
    hostname: server1
  client:
    # 把自己作为注册中心
    register-with-eureka: true
    #从注册中心检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://server2:8002/eureka/,http://server3:8003/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/