server:
  port: 7000
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: eureka-client-ad-sponsor
  datasource:
    url: jdbc:mysql://localhost:3306/ad_data?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: root
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/
logging:
  level:
    com.jd.dao: debug
mybatis:
  mapper-locations: classpath:/mappers/*.xml
