server:
  port: 8003

spring:
  application:
    name: clusterEureka
  profiles: cluster3

eureka:
  instance:
    hostname: server3
  client:
    # 把自己作为注册中心
    register-with-eureka: true
    #从注册中心检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://server1:8001/eureka/,http://server2:8002/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/